package com.project.order_processing_app.entity;

//import com.project.order_processing_app.entity.enums.Role;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

/**
 * User — JPA entity mapped to the "users" table.
 *
 * WHY implement UserDetails?
 *   Spring Security needs a way to load user information during authentication.
 *   By implementing UserDetails directly on this entity, we avoid creating a
 *   separate wrapper class. Spring Security calls getUsername(), getPassword(),
 *   and getAuthorities() on this object during the authentication process.
 *
 * Table name: "users" (not "user" — "user" is a reserved keyword in PostgreSQL)
 *
 * Key decisions:
 *   - Password stored as BCrypt hash ($2a$10$...). NEVER plain text.
 *   - Role stored as STRING enum for readability and forward-compatibility.
 *   - Email is unique at the DB level (enforced by @Column(unique=true)).
 *   - createdAt is set once by @PrePersist and never updated (updatable=false).
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails {

    /** Auto-incremented primary key, generated by the DB sequence */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full display name — used in notifications and dashboard */
    @Column(nullable = false)
    private String name;

    /**
     * Email used as the login identifier (unique per user).
     * @Column(unique = true) creates a UNIQUE INDEX in PostgreSQL.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt-hashed password. Format: $2a$10$<22-char-salt><31-char-hash>
     * BCrypt cost factor 10 → ~100ms to hash — safe against brute force.
     * This field is NEVER returned in any API response (excluded in DTOs).
     */
    @Column(nullable = false)
    private String password;

    /**
     * EnumType.STRING stores "CUSTOMER" or "ADMIN" as text.
     * Safer than ORDINAL — reordering or adding enum values won't corrupt data.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /** Auto-set at creation time, never modified after */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * @PrePersist lifecycle hook: called by Hibernate just before INSERT.
     * Sets createdAt to current UTC time automatically.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // ═══════════════════════════════════════════════════════════
    //  UserDetails interface — required by Spring Security
    // ═══════════════════════════════════════════════════════════

    /**
     * Returns the list of roles/permissions for this user.
     *
     * Spring Security @PreAuthorize("hasRole('ADMIN')") internally checks
     * for the authority string "ROLE_ADMIN", so we must prepend "ROLE_".
     *
     * Example: Role.ADMIN → SimpleGrantedAuthority("ROLE_ADMIN")
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
    }

    /**
     * Spring Security uses this as the "username" for authentication.
     * We use email as the unique login identifier.
     */
    @Override
    public String getUsername() {
        return email;
    }

    // Account status — all true (no account locking implemented in Phase 1)
    @Override public boolean isAccountNonExpired()     { return true; }
    @Override public boolean isAccountNonLocked()      { return true; }
    @Override public boolean isCredentialsNonExpired() { return true; }
    @Override public boolean isEnabled()               { return true; }
}